# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Name of your site (displayed in the header)


author:
  name: EUnS
  email: "euns312510@gmail.com"



minima:
  social_links:
    github: eeeuns
    linkedin: '%EC%9C%A4%EC%8A%B9-%EC%9D%B4-754389186'

# #name: EUnS
title: EUnS's blog


# Build settings
theme: minima

plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed

  # Math equation
markdown: kramdown
excerpt_separator: "\n\n"

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: c++
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1







#default : https://help.github.com/en/github/working-with-github-pages/about-github-pages-and-jekyll#about-jekyll
incremental: false
lsi: false
#highlighter: rouge
# kramdown:
#   input: GFM
#   syntax_highlighter_opts:
#     line_numbers : true 
#     css_class: 'highlight'


# kramdown :
#   syntax_highlighter_opts :
#     span :
#        line_numbers : false 
#     블록 :
#        line_numbers : true

    #highlighter: rouge
# kramdown:
#   input: GFM
#   syntax_highlighter_opts:
#     default_lang: html
#     css_class   : 'syntax'

#   syntax_highlighter_opts:
#     disable : true



google_analytics: G-XQB9DEZZXV



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
