#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: eeeuns

# Short bio or description (displayed in the header)
description: EUnS's blog

disqus: eeeuns
disqus_shortname:    eeeuns


# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars0.githubusercontent.com/u/42970615?s=460&u=e645a705a149c9ebf4f57f559ddaeea007ba01d8&v=4

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: euns312510@gmail.com
  facebook:
  flickr:
  github: eeeuns
  instagram:
  linkedin: '%EC%9C%A4%EC%8A%B9-%EC%9D%B4-754389186'
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: 
  stackoverflow: 
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: G-XQB9DEZZXV

# Enter your Mixpanel project token to activate tracking
mixpanel: f8050bba65fe16fa9054e8656aebef3d

# Set to true if anchorjs should be used to generate "deep anchor links"
anchorjs: true

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://eeeuns.github.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"

tag_page: '/tags/'

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:year/:month/:day/:slug/

future: true

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    default_lang: c++
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

plugins:
  - jekyll-time-to-read

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
